// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace csv2vtodo
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class VTODO : VTODOBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//AndrewAldridge/csv2vtodo\r\n");
            
            #line 13 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 foreach (WorkastCSVFile list in lists) { 
            
            #line default
            #line hidden
            this.Write("BEGIN:VTODO\r\nDTSTAMP:");
            
            #line 15 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.ToString("yyyyMMddTHHmmssZ")));
            
            #line default
            #line hidden
            this.Write("\r\nUID:");
            
            #line 16 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.List));
            
            #line default
            #line hidden
            this.Write("\r\nSUMMARY:List : ");
            
            #line 17 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.List));
            
            #line default
            #line hidden
            this.Write("\r\nEND:VTODO\r\n");
            
            #line 19 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 } 
            
            #line default
            #line hidden
            
            #line 20 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 foreach (WorkastCSVFile listsub in listssub) { 
            
            #line default
            #line hidden
            this.Write("BEGIN:VTODO\r\nDTSTAMP:");
            
            #line 22 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.ToString("yyyyMMddTHHmmssZ")));
            
            #line default
            #line hidden
            this.Write("\r\nUID:");
            
            #line 23 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(listsub.Task));
            
            #line default
            #line hidden
            this.Write("\r\nSUMMARY:List : ");
            
            #line 24 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(listsub.Task));
            
            #line default
            #line hidden
            this.Write("\r\nRELATED-TO:");
            
            #line 25 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(listsub.List));
            
            #line default
            #line hidden
            this.Write("\r\nEND:VTODO\r\n");
            
            #line 27 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 } 
            
            #line default
            #line hidden
            
            #line 28 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 foreach (WorkastCSVFile task in csv) { 
            
            #line default
            #line hidden
            this.Write("BEGIN:VTODO\r\nUID:");
            
            #line 30 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.ID));
            
            #line default
            #line hidden
            this.Write("\r\nDTSTAMP:");
            
            #line 31 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.ToString("yyyyMMddTHHmmssZ")));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 if (task.DueDate != null) { WriteLine("DUE;VALUE=DATE:" + task.DueDate.Value.ToString("yyyyMMdd", System.Globalization.CultureInfo.InvariantCulture)); } 
            
            #line default
            #line hidden
            
            #line 33 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 if (task.StartDate != null) { WriteLine("DTSTART:" + task.StartDate.Value.ToString("yyyyMMddTHHmmssZ", System.Globalization.CultureInfo.InvariantCulture)); } 
            
            #line default
            #line hidden
            this.Write("RELATED-TO:");
            
            #line 34 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 if (task.Subtask == "") { WriteLine(task.List); } else { WriteLine(task.Task); } 
            
            #line default
            #line hidden
            this.Write("STATUS:");
            
            #line 35 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 if (task.Status == "removed") { WriteLine("CANCELLED"); } else if (task.Status == "done") { WriteLine("COMPLETED"); } else { WriteLine("NEEDS-ACTION"); } 
            
            #line default
            #line hidden
            this.Write("SUMMARY:");
            
            #line 36 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 if (task.Subtask == "") { WriteLine(task.Task); } else { WriteLine(task.Subtask);} 
            
            #line default
            #line hidden
            this.Write("ORGANIZER:");
            
            #line 37 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.CreatedBy));
            
            #line default
            #line hidden
            this.Write("\r\nATTENDEE:");
            
            #line 38 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(task.AssignedTo));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 39 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 if (task.CompletedOn != null) { WriteLine("LAST-MODIFIED:" + task.CompletedOn.Value.ToString("yyyyMMdd", System.Globalization.CultureInfo.InvariantCulture)); } 
            
            #line default
            #line hidden
            
            #line 40 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 if (task.Tags != "") { WriteLine("CATEGORIES:" + task.Tags); } 
            
            #line default
            #line hidden
            
            #line 41 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 if (task.Link != "") { WriteLine("COMMENT:" + task.Link); } 
            
            #line default
            #line hidden
            this.Write("END:VTODO\r\n");
            
            #line 43 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"
 } 
            
            #line default
            #line hidden
            this.Write("END:VCALENDAR");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "F:\Documents\Visual Studio 2010\Projects\csv2vtodo\csv2vtodo\VTODO.tt"

private global::System.Collections.Generic.List<WorkastCSVFile> _csvField;

/// <summary>
/// Access the csv parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<WorkastCSVFile> csv
{
    get
    {
        return this._csvField;
    }
}

private global::System.Collections.Generic.List<WorkastCSVFile> _listsField;

/// <summary>
/// Access the lists parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<WorkastCSVFile> lists
{
    get
    {
        return this._listsField;
    }
}

private global::System.Collections.Generic.List<WorkastCSVFile> _listssubField;

/// <summary>
/// Access the listssub parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<WorkastCSVFile> listssub
{
    get
    {
        return this._listssubField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool csvValueAcquired = false;
if (this.Session.ContainsKey("csv"))
{
    this._csvField = ((global::System.Collections.Generic.List<WorkastCSVFile>)(this.Session["csv"]));
    csvValueAcquired = true;
}
if ((csvValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("csv");
    if ((data != null))
    {
        this._csvField = ((global::System.Collections.Generic.List<WorkastCSVFile>)(data));
    }
}
bool listsValueAcquired = false;
if (this.Session.ContainsKey("lists"))
{
    this._listsField = ((global::System.Collections.Generic.List<WorkastCSVFile>)(this.Session["lists"]));
    listsValueAcquired = true;
}
if ((listsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("lists");
    if ((data != null))
    {
        this._listsField = ((global::System.Collections.Generic.List<WorkastCSVFile>)(data));
    }
}
bool listssubValueAcquired = false;
if (this.Session.ContainsKey("listssub"))
{
    this._listssubField = ((global::System.Collections.Generic.List<WorkastCSVFile>)(this.Session["listssub"]));
    listssubValueAcquired = true;
}
if ((listssubValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("listssub");
    if ((data != null))
    {
        this._listssubField = ((global::System.Collections.Generic.List<WorkastCSVFile>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class VTODOBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
